server:
  port: 3344

spring:
  application:
    name:  cloud-com.atguigu.config-center #注册进Eureka服务器的微服务名
  cloud:
    com.atguigu.config:
      server:
        git:
          #uri: https://github.com:pengtao4560/cloud202-springcloud-com.atguigu.config.git
          uri: https://github.com/pengtao4560/cloud202-springcloud-com.atguigu.config
          #uri: https://pengtao4560-admin@bitbucket.org/pengtao4560/springcloud-com.atguigu.config.git
          #git@github.com:zzyybs/springcloud-com.atguigu.config.git #GitHub上面的git仓库名字
          search-paths:
            - cloud202-springcloud-com.atguigu.config
          username: pengtao450
          password: 1234Pt..
      ####读取分支
      label: master

#rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'


