server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #uri: https://github.com:pengtao4560/cloud202-springcloud-config.git
          uri: https://github.com/pengtao4560/cloud202-springcloud-config
          #git@github.com:zzyybs/springcloud-config.git #GitHub上面的git仓库名字
          search-paths:
            - cloud202-springcloud-config
          username: pengtao450
          password: 1234Pt..
      ####读取分支
      label: master
#rabbitmq相关配置
#rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'


